#!/usr/bin/env ruby
# This script automagically[TM] generates the various "Waifu" types
# (c) 2015 nilsding

$: << File.expand_path('../../../', __FILE__)
require 'yourwaifu/defaults'
require 'erb'

script_name = File.basename __FILE__
types = Dir[YourWaifu::LIST_PATH + '/*.yml'].map{ |x| File.basename(x).sub(/\.yml/, '') }
erb = ERB.new(DATA.read)

types.each do |thing|
  puts "require 'yourwaifu/types/#{thing}'"
  File.open "#{thing}.rb", 'w' do |f|
    f.puts erb.result(binding)
  end
end

__END__
# This file was generated by <%= File.basename script_name %>
# <%= Time.now.strftime '%F %T' %>

module YourWaifu
  class <%= thing.capitalize %> < YourWaifu::Base
    def config_name
      '<%= thing %>'
    end
  end
end
